### ISSUE TITLE
[6월 21일~ 6월 28일] 김진영 TODO

### ISSUE THREAD

**Issue by jy-kkkim** [testteset/testset#7]
## 주요 내용
- [x] Issues Rules 정리
- [x] Issues Template 생성
- [ ] Git Rules 정리

## 상세 내용
1. Issues Rules 정리
    - [ Issues ] 를 통해 프로젝트를 관리하고자 Issues 규칙을 정한다.
    - Issues Template을 생성하고 만들어 놓은 Template만을 사용하여 Issues를 생성할 것

2. Issues Template 생성
    - 회의록 : 정기 회의, 아이디어 회의, 버그 회의 등 회의를 한 뒤 회의 내용을 남겨놓기 위함
    - development : 실제 개발을 위해 완료되어야 하는 내용을 작성
    - todo : 한 주 단위로 각자 해야 할 내용을 작성

3. Git Rules 정리
    - Source Tree + Git Flow 사용법 숙지 및 정리
    - Commit Rules 작성

## 특이사항
살려줘
